# Generated by Django 5.2.1 on 2025-06-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True, 'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='clickhistory',
            options={'managed': False, 'ordering': ['-timestamp'], 'verbose_name': 'Click History', 'verbose_name_plural': 'Click Histories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'managed': True, 'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': False, 'ordering': ['-time'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False, 'ordering': ['-posted_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicant',
            options={'managed': True, 'ordering': ['-application_time'], 'verbose_name': 'Job Applicant', 'verbose_name_plural': 'Job Applicants'},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'managed': True, 'verbose_name': 'Job Seeker', 'verbose_name_plural': 'Job Seekers'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False, 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False, 'ordering': ['-time'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'managed': False, 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
    ]
