# Generated by Django 5.2.1 on 2025-06-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': False, 'ordering': ['-posted_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
