# Generated by Django 5.2.1 on 2025-06-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobseeker_password_alter_jobseeker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume_url',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
