# Generated by Django 5.2.1 on 2025-06-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobseeker_profile_pic_jobseeker_resume_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='password',
        ),
    ]
