# Generated by Django 5.2.1 on 2025-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_jobseeker_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='password',
            field=models.CharField(blank=True, db_column='password', max_length=255, null=True),
        ),
    ]
